services:
  storybook-api:
    container_name: storybook-api-container
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env

  storybook-ui:
    container_name: storybook-ui-container
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run streamlit_app.py \
      --server.port 8501 \
      --server.address 0.0.0.0 \
      --server.headless true \
      --server.enableCORS false
    ports:
      - "8501:8501"
    depends_on:
      - storybook-api
    env_file:
      - .env
    environment:
      - IN_DOCKER=1