from openai import OpenAI
from src.config import settings
from src.prompts import build_story_prompt, build_gpt_system_prompt

# Set up OpenAI client
client = OpenAI(api_key=settings.OPENAI_API_KEY)

def generate_story(caption: str) -> str:
    """
    Generates a short, funny children's story based on an image caption.

    Args:
        caption (str): The image description generated by BLIP.

    Returns:
        str: A short and humorous story.
    """
    prompt = build_story_prompt(caption)

    response = client.chat.completions.create(
        model=settings.GPT_MODEL,
        messages=[
            {"role": "system", "content": build_gpt_system_prompt()},
            {"role": "user", "content": prompt}
        ],
        temperature=0.9,
        max_tokens=200
    )

    story = response.choices[0].message.content.strip()
    return story