import os
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Set up OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def generate_story(caption: str) -> str:
    """
    Generates a short, funny children's story based on an image caption.

    Args:
        caption (str): The image description generated by BLIP.

    Returns:
        str: A short and humorous story.
    """
    prompt = (
        f"Here is a description of an image: '{caption}'. "
        "Write a very short (max 100 words) and very funny children's story based on this image. "
        "The story should be playful, a bit silly, and include magical or unexpected elements."
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a brilliant and funny children's book author."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.9,
        max_tokens=200
    )

    story = response.choices[0].message.content.strip()
    return story
